# This is a basic workflow to help you get started with Actions

name: Deploy Staging

on:
  push:
    branches: [ staging ]
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run:  apk add ruby && gem install mustache
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@target-branch
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          destination-github-username: 'Nehfamim'
          destination-repository-name: 'burger-review-staging'
          user-email: staging-ci@nehfamim.org
          commit-message: $GITHUB_REF
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
